name: main
on:
  push:
    branches: [ main ]
    
env:
  VOTTING: 'false'
  GRAFANA: 'false'
  PROMETHEUS: 'true'

jobs:
  test_kubectl:
    runs-on: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v2
      
      - name: Install kubectl
        run: |
          echo $PATH
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
          chmod +x kubectl
          mkdir -p ~/.local/bin/kubectl
          mv ./kubectl ~/.local/bin/kubectl
      
      - name: gcloud
        uses: google-github-actions/setup-gcloud@master

        with:
          version: '299.0.0'

          project_id: playground-s-11-66ae0f5d 
          service_account_key: ${{ secrets.GCP_SECRET }}
      
      - name: gcloud authentication
        run: |-
          GCP_CLUSTER="cluster-1"
          GCP_REGION="us-central1-c"

          gcloud container clusters get-credentials "${GCP_CLUSTER}" --region "${GCP_REGION}"
          
      - name: Install voting_app
        if: ${{ env.VOTTING == 'true' }}
        run: |-
          kubectl create namespace vote
          kubectl apply -f voting_app/.
          
      - name: Install grafana
        if: ${{ env.GRAFANA == 'true' }}
        run: |-          
          kubectl apply -f grafana_install/. -n monitoring
       
      - name: Install Prometheus
        if: ${{ env.PROMETHEUS == 'true' }}
        run: |-
          ACCOUNT=$(gcloud info --format='value(config.account)')
          kubectl create clusterrolebinding owner-cluster-admin-binding --clusterrole cluster-admin --user $ACCOUNT
          kubectl apply -f prometheus_install/.  -n monitoring
          
      - name: Test kubectl
        run: |
          sudo su
          kubectl cluster-info
          kubectl get pods -A
      
      - name: dependencies
        run: |-
          .github/scripts/dependencies.sh
      

