name: Test kubectl
on:
  push:
    branches: [ main ]

jobs:
  test_kubectl:
    runs-on: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v2
      
      - name: Install kubectl
        run: |
          echo $PATH
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
          chmod +x kubectl
          mkdir -p ~/.local/bin/kubectl
          mv ./kubectl ~/.local/bin/kubectl
      
      - name: gcloud
        uses: google-github-actions/setup-gcloud@master

        with:
          version: '299.0.0'

          project_id: playground-s-11-66ae0f5d 
          service_account_key: ${{ secrets.GCP_SECRET }}
      
      - name: gcloud authentication
        run: |-
          GCP_CLUSTER="cluster-1"
          GCP_REGION="us-central1-c"

          gcloud container clusters get-credentials "${GCP_CLUSTER}" --region "${GCP_REGION}"
          
      - name: Install Wordpress
        run: |-
          kubectl delete -f k8s_wordpress/.
      
      - name: Test kubectl
        run: |
          sudo su
          kubectl cluster-info
          kubectl get pods -A
      
      - name: dependencies
        run: |-
          .github/scripts/dependencies.sh
      

