name: main
on:
  push:
    branches: [ main ]
    
env:
  VOTTING: 'false'
  GRAFANA: 'false'
  PROMETHEUS: 'true'
  KUBE_METRICS: 'true'

jobs:
  test_kubectl:
    runs-on: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v2
      
      - name: gcloud
        uses: google-github-actions/setup-gcloud@master

        with:
          version: '299.0.0'

          project_id: playground-s-11-66ae0f5d 
          service_account_key: ${{ secrets.GCP_SECRET }}
      
      - name: gcloud authentication
        run: |-
          GCP_CLUSTER="cluster-1"
          GCP_REGION="us-central1-c"

          gcloud container clusters get-credentials "${GCP_CLUSTER}" --region "${GCP_REGION}"
          
      - name: Check if necessary namespaces exists
        run: |-
          .github/scripts/check_namespaces.sh
          
      - name: Install Kube metrics
        if: ${{ env.KUBE_METRICS == 'true' }}
        run: |-          
          kubectl apply -f kube_metrics/.
          
      - name: Install voting_app
        if: ${{ env.VOTTING == 'true' }}
        run: |-
          kubectl apply -f voting_app/.
          
      - name: Install grafana
        if: ${{ env.GRAFANA == 'true' }}
        run: |-          
          kubectl apply -f grafana_install/. -n monitoring
       
      - name: Install Prometheus
        if: ${{ env.PROMETHEUS == 'true' }}
        run: |-          
          kubectl apply -f prometheus_install/.  -n monitoring
          
      - name: Test kubectl
        run: |
          sudo su
          kubectl cluster-info
          kubectl get pods -A

      

