name: Test kubectl
on:
  push:
    branches: [ main ]

jobs:
  test_kubectl:
    runs-on: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v2
      - name: Install kubectl
        run: |
          echo $PATH
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
          chmod +x kubectl
          mkdir -p ~/.local/bin/kubectl
          mv ./kubectl ~/.local/bin/kubectl
      - name: gcloud
        uses: google-github-actions/setup-gcloud@master

        with:
          version: '299.0.0'

          project_id: playground-s-11-9150f5a9
          service_account_key: ${{ secrets.GCP_SECRET }}
      - name: gcloud authentication
        run: |-
          GCP_CLUSTER="gke_playground-s-11-9150f5a9_us-central1-c_cluster-1"
          GCP_REGION="us-central1-c"

          gcloud container clusters get-credentials "${GCP_CLUSTER}" --region "${GCP_REGION}"
      - name: Save kubeconfig to github var
        # kubeconfig path is saved as github var to be used by helm
        run: |
          echo ${{ secrets.KUBE_CONFIG }} | base64 --decode > $RUNNER_TEMP/config
          echo "kubeconfig=$RUNNER_TEMP/config" >> $GITHUB_ENV
      - name: Test kubectl
        env:
          KUBECONFIG: "${{ env.kubeconfig }}"
        run: |
          sudo su
          kubectl cluster-info
          kubectl get pods -A
